### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by TexBlock** [ThinkingStudios/ContingameIME#1]
- [ ] 1.20.4
- [ ] 1.20.6
- [ ] 1.21
- [ ] Kotlin -> Java
- [x] Move to Architectury API
  - [x] 1.20.x
  - [x] 1.19.3/4
  - [x] 1.19.2
  - [x] 1.18.x
  - [x] 1.17.x
  - [x] 1.16.5
- [ ] Use latest IngameIME-CLib ([Common](https://github.com/Windmill-City/IngameIME-Common)/[Win32](https://github.com/Windmill-City/IngameIME_Win32)/[Linux](https://github.com/Windmill-City/IngameIME_Linux)/[MacOS](https://github.com/Windmill-City/IngameIME_MacOs))

**Comment by TexBlock** [comment]
- [ ] port to 1.20 (Forge&Fabric)
